In [9]:
import numpy as np
import pandas as pd 
import statsmodels.formula.api as smf
import seaborn as sns
import matplotlib.pyplot as plt
import pingouin as pg

In [10]:
data = pd.read_csv('../data/snack_consumer_sensory_dataset.csv')
data.head()

,respondent_id,market,age,gender,product,overall_liking,sweetness,crunchiness,oiliness,aftertaste
0,10001,UK,34,Female,A_CrunchyClassic,7,3.0,6.1,5.5,3.9
1,10001,UK,34,Female,B_SweetSpicy,8,7.1,7.1,3.9,5.9
2,10001,UK,34,Female,C_LightBaked,4,3.1,6.5,4.6,2.9
3,10001,UK,34,Female,D_RichCheesy,3,5.2,4.1,6.3,6.0
4,10002,US,50,Female,A_CrunchyClassic,7,2.7,7.9,5.0,2.1

In [11]:

model = smf.mixedlm(
    "overall_liking ~ product",
    data,
    groups=data["respondent_id"]
)

result = model.fit()

d:\Evaluation-Task-CodeBricks\.venv\Lib\site-packages\statsmodels\regression\mixed_linear_model.py:2237: ConvergenceWarning: The MLE may be on the boundary of the parameter space.
  warnings.warn(msg, ConvergenceWarning)

In [ ]:

posthoc = pg.pairwise_tests(
    data=data,
    dv="overall_liking",
    within="product",
    subject="respondent_id",
    padjust="bonf"  
)
posthoc

,Contrast,A,B,Paired,Parametric,T,dof,alternative,p_unc,p_corr,p_adjust,BF10,hedges
0,product,A_CrunchyClassic,B_SweetSpicy,True,True,-6.990488,219.0,two-sided,3.264077e-11,1.958446e-10,bonf,2.209e+08,-0.664245
1,product,A_CrunchyClassic,C_LightBaked,True,True,-5.292163,219.0,two-sided,2.928892e-07,1.757335e-06,bonf,3.397e+04,-0.511264
2,product,A_CrunchyClassic,D_RichCheesy,True,True,13.067530,219.0,two-sided,3.120552e-29,1.872331e-28,bonf,1.037e+26,1.198522
3,product,B_SweetSpicy,C_LightBaked,True,True,1.609869,219.0,two-sided,1.088669e-01,6.532015e-01,bonf,0.269,0.157695
4,product,B_SweetSpicy,D_RichCheesy,True,True,19.077420,219.0,two-sided,1.881532e-48,1.128919e-47,bonf,1.047e+45,1.812599
5,product,C_LightBaked,D_RichCheesy,True,True,17.750441,219.0,two-sided,2.820742e-44,1.692445e-43,bonf,7.665e+40,1.678846